### PR TITLE
HAFM NH90 Upgrades and Fixes

### PR DESCRIPTION
**Pull request by AChesheireCat**
- Adds Virtual Garage skin functionality

- Adds Kimi HMD functionality to both NH90 variants

- Fixes Armed NH90 seat capacity being more than physically capable/shown on model (was 16pax, now is 8pax + 2 gunners + 2 pilots)

- Adds Finnish NH90 skin authored by troska and Centurion_101 via SFP: Finnish Forces Pack (https://steamcommunity.com/sharedfiles/filedetails/?id=917042703)

- Adds ACE Fast Roping functionality (yuck)

### CODE REVIEW

**Review by kil0byt3 — DISMISSED** [review]
didn't realize how many lines there are in a Kimi patch

looks fine though, other stuff looks good too 

i'm not entirely sure the comment on line 74 will work because it's inside a bracket, but maybe it's fine

you test this?

**Review by TheCandianVendingMachine — CHANGES_REQUESTED** [review]
why do we need to define the hud for each vehicle? surely it’ll be defined and inherited from the base?

21,000 lines for some helicopters is a code smell, i just want to make sure

**Comment by AChesheireCat** [comment]
Yup, although not by building my own version of POTATO - just via a local mod. The RPT didn't spit any errors out, for what it's worth. 

The only thing I didn't test is the fast rope stuff, because yuck and I only tested in SP lol

**Comment by lambdatiger** [comment]
There are also decently sized blocks of config that are just commented, do we need to keep them for some reason?

**Review by PabstMirror — CHANGES_REQUESTED** [review]
```
ErrorMessage: File z\potato\addons\miscFixes\patchhafm\config.cpp, line 10734: /CfgVehicles/NH90.UserActions: Undefined base class 'UserActions'
Application terminated intentionally

**Comment by AChesheireCat** [comment]
Based out of the wrong folder and encountered error due to missing required mods; have submitted adjacent pull request to resolve issue and rebase folder

This is the new PR: https://github.com/BourbonWarfare/POTATO/pull/577

**Pull request closed without merging**
