### PR TITLE
assingGear - Selectable "No optic" and Fixed List 

### PR DESCRIPTION
**Pull request by lambdatiger**
This PR adds a no optic option when custom optics are allowed and provides a CBA option to not hide the current optic from hte list.

### CODE REVIEW

**Review by TheCandianVendingMachine — APPROVED** [review]
why `#` over select? operator precidence affecting this?

**Comment by lambdatiger** [comment]
> why `#` over select? operator precidence affecting this?

I use # by default, do you want it to be select? Originally it was `primaryWeaponItems _player #2` which works but is less readable so I added the parenthesis.

**Comment by TheCandianVendingMachine** [comment]
i dont care about it, just wanted to know if i had a blindspot

**Review by PabstMirror — APPROVED** [review]
lgtm
I don't think we need a setting or could make it default true but it's fine as is

**Comment by lambdatiger** [comment]
I've been trying to avoid changing default behavior since I know some people like hiding the current optic. I think your modification helps make it a bit clearer which is current and we could get rid of it, let me do a quick "survey" and we can cut it out if there's no opposition.

**Comment by lambdatiger** [comment]
Alright based on feedback I'll remove the option

**Pull request merged**
