### PR TITLE
M240, PKM, M249 Recoil Changes

### PR DESCRIPTION
**Pull request by AChesheireCat**
This makes the aforementioned weapons suck so much less.

### CODE REVIEW

**Comment by AChesheireCat** [comment]
Example of the new recoil: https://discord.com/channels/204621032428929025/285837079139844096/1068308429631926302

(I believe these are older versions, but it is indicative of how the recoil has been changed.)

**Review by PabstMirror — APPROVED** [review]
sorry, I forgot to get this in
looks good to go

**Comment by AChesheireCat** [comment]
usable MMG recoil soon(tm)

i am vibrating with excitement LOL

**Comment by kil0byt3** [comment]
> Do i need to do anything on my part? I don't think I have perms to merge o.o

@AChesheireCat pabst will merge in next modupdate, nothing needed from your end

**Pull request merged**
