### PR TITLE
More vestBackpacks

### PR DESCRIPTION
**Pull request by AChesheireCat**
- Fixes some smersh vestBackpacks having incorrectly colored ui pictures

- Adds CWRIII ALICE LBE

- Adds M23 chest rigs in TKE and OD Green

- Adds 6Sh92 chest rigs

- Adds Raven vest

### CODE REVIEW

**Comment by kil0byt3** [comment]
vackpacks

**Review by lambdatiger — COMMENTED** [review]
All of your new (and old) backpacks converted from vests don't have the same container size and mass as the vests, which is ok. For example, the alice and alice mg vests both have a container space of 140 and mass of 15, while yours have maximum loads of 160 and 190, and masses of 25 and 30 respectively. I can't really identify your relationship between the two, could you help clarify?

**Comment by AChesheireCat** [comment]
> I can't really identify your relationship between the two, could you help clarify?

Yeah, absolutely - these vest backpacks were initially intended to be used with vests that had limited-to-no carrying capacity so they needed to have a large enough carrying capacity to be able to fit our full combat load + whatever we typically put into our backpack's inventory (medical items, etc.). The weight is me thinking that it needed a balancing measure for how much they can carry if combined with vests with typical carrying capacities, but I'm so-so on that now.

**Comment by lambdatiger** [comment]
Cool, I think you're the main consumer of the vest backpacks. So if it all works and you're happy with it, I'm happy with it.

**Review by lambdatiger — APPROVED** [review]

**Review by PabstMirror — APPROVED** [review]

**Pull request merged**
