### PR TITLE
add player screams when they go unconscious

### PR DESCRIPTION
**Pull request by kil0byt3**
- I don't think we currently have a feature to do this but maybe
- it seems to double scream in singleplayer but I dont think it will in mp
- anecdotal evidence from various folks seems to think we don't have anything like this currently

### CODE REVIEW

**Comment by kil0byt3** [comment]
ready 4 merge

**Comment by PabstMirror** [comment]
it oddly doesn't work for me
I don't think unconscious units can talk

e.g.
if I try
```
[] spawn { sleep 1;
cursorObject say3D [selectRandom potato_player_screams_soundList, 200, 1, false];
sleep 0.1;
[cursorObject, true, 60000] call ace_medical_fnc_setUnconscious;
};
```
the scream gets cut off after a fraction of a second

**Comment by PabstMirror** [comment]
maybe switch to `playSound3D`?

**Comment by kil0byt3** [comment]
I'll try that this week

**Comment by kil0byt3** [comment]
Superseded with ACE Moaning

**Pull request closed without merging**
