### PR TITLE
add mag for every single variant feasible

### PR DESCRIPTION
**Pull request by TheCandianVendingMachine**
clutters the hell out of the magazine dialog, but people allegedly are okay with it so

### CODE REVIEW

**Comment by Alablm** [comment]
Personally speaking I never use the all magazines dialog anyways, and for our purposes it shouldn't matter too much

**Review by Alablm — COMMENTED** [review]
Looks good syntax wise. Cant test personally, just a visual review. 

Formatting looks strange, but I think its just because I'm on mobile. Can someone confirm that the indentation isint actually fucked in the submitted code for me?

**Comment by Alex6511** [comment]
Stupid question but have you thought about just writing a python script or something to auto generate this?

**Comment by TheCandianVendingMachine** [comment]
Unless if I write an image processing algorithm it will catch duplicates due to inconsistent naming and whatnot. It takes like 30 minutes to manually do it, not worth automating

**Pull request merged**
