### PR TITLE
Increase illumination from vanilla and rhs flares

### PR DESCRIPTION
**Pull request by PabstMirror**

### CODE REVIEW

**Comment by AACO** [comment]
Shouldn't this be (mostly) addressed by https://github.com/acemod/ACE3/pull/4506 ?

**Comment by PabstMirror** [comment]
- This PR will work for us right away, with no change to loadouts
- The ACE PR won't touch RHS flares, which we are going to want to make it symetrical
- I'm not sure if that ace PR is the right way, I'm also leaning towards adding new magazines. If I can figure out how to do it.

**Comment by AACO** [comment]
As to point 3, good fucking luck, maybe the Tanoa changes fixed it, but I tried ~3 hours to get it working for the UGLs to very limited success.

**Comment by AACO** [comment]
One last thing before merging this, should we add this to the BWA3 gustav illumination rounds? It might be too niche to worry about, just wanted to bring it up.

**Pull request merged**
