### PR TITLE
OCAP implementation and compatibility with POTATO End Mission fnc

### PR DESCRIPTION
**Pull request by kil0byt3**
draft for now

### CODE REVIEW

**Comment by kil0byt3** [comment]
OCAP 2.0 automatically ends recording when it detects `BIS_fnc_endMission` or `BIS_fnc_endMissionServer`

I was able to implement without changing anything in POTATO, see link posted on Discord

There are more customizations we could make in this PR later, however, like adding tags to the missions i.e. TvT or Coop so they are sorted nicely on the web interface

I'll review that possibility after we test it for a bit

**Comment by DanThomas64** [comment]
I think that we can close this now no?

**Comment by kil0byt3** [comment]
> I think that we can close this now no?

I still want to do this: `adding tags to the missions i.e. TvT or Coop so they are sorted nicely on the web interface`

**Review by DanThomas64 — CHANGES_REQUESTED** [review]
Suggest using 
`getMissionConfigValue QEGVAR(missionTesting missionType)` to get the type of mission. 

Technically The OCAP data would be saved in `endMission` and not `uihook_endMission` so I would create the debug message from the result of saving the OCAP recording based on the output of the ocap_fnc_exportData function.

**Review by TheCandianVendingMachine — APPROVED** [review]

**Pull request merged**
